/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tdt4250.xss.XSSRuntimeModule;
import tdt4250.xss.XSSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XSSIdeSetup extends XSSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XSSRuntimeModule(), new XSSIdeModule()));
	}
	
}
