/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXSSValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(tdt4250.xss.xSS.XSSPackage.eINSTANCE);
		return result;
	}
}
