/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import tdt4250.xss.xSS.CustomProperty;
import tdt4250.xss.xSS.SubRule;
import tdt4250.xss.xSS.XSSPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Custom Property</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.impl.CustomPropertyImpl#getSubRules <em>Sub Rules</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomPropertyImpl extends XPropertyImpl implements CustomProperty
{
  /**
   * The cached value of the '{@link #getSubRules() <em>Sub Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubRules()
   * @generated
   * @ordered
   */
  protected EList<SubRule> subRules;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSSPackage.Literals.CUSTOM_PROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SubRule> getSubRules()
  {
    if (subRules == null)
    {
      subRules = new EObjectContainmentEList<SubRule>(SubRule.class, this, XSSPackage.CUSTOM_PROPERTY__SUB_RULES);
    }
    return subRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XSSPackage.CUSTOM_PROPERTY__SUB_RULES:
        return ((InternalEList<?>)getSubRules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XSSPackage.CUSTOM_PROPERTY__SUB_RULES:
        return getSubRules();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XSSPackage.CUSTOM_PROPERTY__SUB_RULES:
        getSubRules().clear();
        getSubRules().addAll((Collection<? extends SubRule>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XSSPackage.CUSTOM_PROPERTY__SUB_RULES:
        getSubRules().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XSSPackage.CUSTOM_PROPERTY__SUB_RULES:
        return subRules != null && !subRules.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //CustomPropertyImpl
