/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tdt4250.xss.xSS.XSSPackage;
import tdt4250.xss.xSS.XSelector;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XSelector</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XSelectorImpl extends MinimalEObjectImpl.Container implements XSelector
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XSelectorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSSPackage.Literals.XSELECTOR;
  }

} //XSelectorImpl
