/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tdt4250.xss.xSS.XSSPackage;
import tdt4250.xss.xSS.XStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XStatement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XStatementImpl extends MinimalEObjectImpl.Container implements XStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSSPackage.Literals.XSTATEMENT;
  }

} //XStatementImpl
