/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import tdt4250.xss.tests.XSSInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(XSSInjectorProvider.class)
@SuppressWarnings("all")
public class XSSParsingTest {
  @Inject
  private /* ParseHelper<stylesheet> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field XSSParsingTest.parseHelper refers to the missing type stylesheet"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
