/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tdt4250.xss.ui.internal.XssActivator;

public class XSSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XssActivator.getInstance().getInjector("tdt4250.xss.XSS");
	}

}
