/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XSSUiModule extends AbstractXSSUiModule {

	public XSSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
