/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.CustomProperty#getSubRule <em>Sub Rule</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getCustomProperty()
 * @model
 * @generated
 */
public interface CustomProperty extends XProperty
{
  /**
   * Returns the value of the '<em><b>Sub Rule</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.SubRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Rule</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getCustomProperty_SubRule()
   * @model containment="true"
   * @generated
   */
  EList<SubRule> getSubRule();

} // CustomProperty
