/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.GroupProperty#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getGroupProperty()
 * @model
 * @generated
 */
public interface GroupProperty extends XProperty
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.XStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getGroupProperty_Statements()
   * @model containment="true"
   * @generated
   */
  EList<XStatement> getStatements();

} // GroupProperty
