/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.GroupSelector#getName <em>Name</em>}</li>
 *   <li>{@link tdt4250.xss.xSS.GroupSelector#getSubSelectors <em>Sub Selectors</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getGroupSelector()
 * @model
 * @generated
 */
public interface GroupSelector extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tdt4250.xss.xSS.XSSPackage#getGroupSelector_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tdt4250.xss.xSS.GroupSelector#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sub Selectors</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.Selector}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Selectors</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getGroupSelector_SubSelectors()
   * @model containment="true"
   * @generated
   */
  EList<Selector> getSubSelectors();

} // GroupSelector
