/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.MultiStatement#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getMultiStatement()
 * @model
 * @generated
 */
public interface MultiStatement extends XMultiStatement
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' attribute.
   * @see #setProperty(String)
   * @see tdt4250.xss.xSS.XSSPackage#getMultiStatement_Property()
   * @model
   * @generated
   */
  String getProperty();

  /**
   * Sets the value of the '{@link tdt4250.xss.xSS.MultiStatement#getProperty <em>Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' attribute.
   * @see #getProperty()
   * @generated
   */
  void setProperty(String value);

} // MultiStatement
