/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi Ref Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.MultiRefStatement#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getMultiRefStatement()
 * @model
 * @generated
 */
public interface MultiRefStatement extends XMultiStatement
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(CustomProperty)
   * @see tdt4250.xss.xSS.XSSPackage#getMultiRefStatement_Property()
   * @model
   * @generated
   */
  CustomProperty getProperty();

  /**
   * Sets the value of the '{@link tdt4250.xss.xSS.MultiRefStatement#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(CustomProperty value);

} // MultiRefStatement
