/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>stylesheet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tdt4250.xss.xSS.stylesheet#getCustomSelectors <em>Custom Selectors</em>}</li>
 *   <li>{@link tdt4250.xss.xSS.stylesheet#getCustomProperties <em>Custom Properties</em>}</li>
 *   <li>{@link tdt4250.xss.xSS.stylesheet#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see tdt4250.xss.xSS.XSSPackage#getstylesheet()
 * @model
 * @generated
 */
public interface stylesheet extends EObject
{
  /**
   * Returns the value of the '<em><b>Custom Selectors</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.XSelector}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Selectors</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getstylesheet_CustomSelectors()
   * @model containment="true"
   * @generated
   */
  EList<XSelector> getCustomSelectors();

  /**
   * Returns the value of the '<em><b>Custom Properties</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.XProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Properties</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getstylesheet_CustomProperties()
   * @model containment="true"
   * @generated
   */
  EList<XProperty> getCustomProperties();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link tdt4250.xss.xSS.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see tdt4250.xss.xSS.XSSPackage#getstylesheet_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // stylesheet
