/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XSelector</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tdt4250.xss.xSS.XSSPackage#getXSelector()
 * @model
 * @generated
 */
public interface XSelector extends EObject
{
} // XSelector
