/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see tdt4250.xss.xSS.XSSFactory
 * @model kind="package"
 * @generated
 */
public interface XSSPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xSS";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "tdt4250.xss.model";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xSS";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XSSPackage eINSTANCE = tdt4250.xss.xSS.impl.XSSPackageImpl.init();

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.stylesheetImpl <em>stylesheet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.stylesheetImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getstylesheet()
   * @generated
   */
  int STYLESHEET = 0;

  /**
   * The feature id for the '<em><b>Custom Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLESHEET__CUSTOM_SELECTORS = 0;

  /**
   * The number of structural features of the '<em>stylesheet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLESHEET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.GroupSelectorImpl <em>Group Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.GroupSelectorImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupSelector()
   * @generated
   */
  int GROUP_SELECTOR = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Sub Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR__SUB_SELECTORS = 1;

  /**
   * The number of structural features of the '<em>Group Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.SelectorImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 2;

  /**
   * The feature id for the '<em><b>Names</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__NAMES = 0;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.stylesheet <em>stylesheet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>stylesheet</em>'.
   * @see tdt4250.xss.xSS.stylesheet
   * @generated
   */
  EClass getstylesheet();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.stylesheet#getCustomSelectors <em>Custom Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Custom Selectors</em>'.
   * @see tdt4250.xss.xSS.stylesheet#getCustomSelectors()
   * @see #getstylesheet()
   * @generated
   */
  EReference getstylesheet_CustomSelectors();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.GroupSelector <em>Group Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Selector</em>'.
   * @see tdt4250.xss.xSS.GroupSelector
   * @generated
   */
  EClass getGroupSelector();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.GroupSelector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tdt4250.xss.xSS.GroupSelector#getName()
   * @see #getGroupSelector()
   * @generated
   */
  EAttribute getGroupSelector_Name();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.GroupSelector#getSubSelectors <em>Sub Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Selectors</em>'.
   * @see tdt4250.xss.xSS.GroupSelector#getSubSelectors()
   * @see #getGroupSelector()
   * @generated
   */
  EReference getGroupSelector_SubSelectors();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see tdt4250.xss.xSS.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute list '{@link tdt4250.xss.xSS.Selector#getNames <em>Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Names</em>'.
   * @see tdt4250.xss.xSS.Selector#getNames()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Names();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XSSFactory getXSSFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.stylesheetImpl <em>stylesheet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.stylesheetImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getstylesheet()
     * @generated
     */
    EClass STYLESHEET = eINSTANCE.getstylesheet();

    /**
     * The meta object literal for the '<em><b>Custom Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLESHEET__CUSTOM_SELECTORS = eINSTANCE.getstylesheet_CustomSelectors();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.GroupSelectorImpl <em>Group Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.GroupSelectorImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupSelector()
     * @generated
     */
    EClass GROUP_SELECTOR = eINSTANCE.getGroupSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP_SELECTOR__NAME = eINSTANCE.getGroupSelector_Name();

    /**
     * The meta object literal for the '<em><b>Sub Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_SELECTOR__SUB_SELECTORS = eINSTANCE.getGroupSelector_SubSelectors();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.SelectorImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Names</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__NAMES = eINSTANCE.getSelector_Names();

  }

} //XSSPackage
