/**
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.xSS;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see tdt4250.xss.xSS.XSSFactory
 * @model kind="package"
 * @generated
 */
public interface XSSPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xSS";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "tdt4250.xss.model";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xSS";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XSSPackage eINSTANCE = tdt4250.xss.xSS.impl.XSSPackageImpl.init();

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.stylesheetImpl <em>stylesheet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.stylesheetImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getstylesheet()
   * @generated
   */
  int STYLESHEET = 0;

  /**
   * The feature id for the '<em><b>Custom Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLESHEET__CUSTOM_SELECTORS = 0;

  /**
   * The feature id for the '<em><b>Custom Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLESHEET__CUSTOM_PROPERTIES = 1;

  /**
   * The number of structural features of the '<em>stylesheet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STYLESHEET_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.XSelectorImpl <em>XSelector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.XSelectorImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXSelector()
   * @generated
   */
  int XSELECTOR = 1;

  /**
   * The number of structural features of the '<em>XSelector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSELECTOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.GroupSelectorImpl <em>Group Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.GroupSelectorImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupSelector()
   * @generated
   */
  int GROUP_SELECTOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR__NAME = XSELECTOR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sub Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR__SUB_SELECTORS = XSELECTOR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Group Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_SELECTOR_FEATURE_COUNT = XSELECTOR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.SelectorImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__NAME = 0;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.XPropertyImpl <em>XProperty</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.XPropertyImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXProperty()
   * @generated
   */
  int XPROPERTY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPROPERTY__NAME = 0;

  /**
   * The number of structural features of the '<em>XProperty</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPROPERTY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.CustomPropertyImpl <em>Custom Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.CustomPropertyImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getCustomProperty()
   * @generated
   */
  int CUSTOM_PROPERTY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_PROPERTY__NAME = XPROPERTY__NAME;

  /**
   * The feature id for the '<em><b>Sub Rule</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_PROPERTY__SUB_RULE = XPROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Custom Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_PROPERTY_FEATURE_COUNT = XPROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.SubRuleImpl <em>Sub Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.SubRuleImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSubRule()
   * @generated
   */
  int SUB_RULE = 6;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_RULE__PROPERTY = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_RULE__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Sub Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.ExpressionImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.GroupPropertyImpl <em>Group Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.GroupPropertyImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupProperty()
   * @generated
   */
  int GROUP_PROPERTY = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_PROPERTY__NAME = XPROPERTY__NAME;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_PROPERTY__STATEMENTS = XPROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Group Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_PROPERTY_FEATURE_COUNT = XPROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.XStatementImpl <em>XStatement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.XStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXStatement()
   * @generated
   */
  int XSTATEMENT = 9;

  /**
   * The number of structural features of the '<em>XStatement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSTATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.XSingleStatementImpl <em>XSingle Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.XSingleStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXSingleStatement()
   * @generated
   */
  int XSINGLE_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSINGLE_STATEMENT__VALUE = XSTATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>XSingle Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSINGLE_STATEMENT_FEATURE_COUNT = XSTATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.SingleRefStatementImpl <em>Single Ref Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.SingleRefStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSingleRefStatement()
   * @generated
   */
  int SINGLE_REF_STATEMENT = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_REF_STATEMENT__VALUE = XSINGLE_STATEMENT__VALUE;

  /**
   * The feature id for the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_REF_STATEMENT__PROPERTY = XSINGLE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Single Ref Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_REF_STATEMENT_FEATURE_COUNT = XSINGLE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.SingleStatementImpl <em>Single Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.SingleStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSingleStatement()
   * @generated
   */
  int SINGLE_STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_STATEMENT__VALUE = XSINGLE_STATEMENT__VALUE;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_STATEMENT__PROPERTY = XSINGLE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Single Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_STATEMENT_FEATURE_COUNT = XSINGLE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.XMultiStatementImpl <em>XMulti Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.XMultiStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXMultiStatement()
   * @generated
   */
  int XMULTI_STATEMENT = 13;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMULTI_STATEMENT__STATES = 0;

  /**
   * The number of structural features of the '<em>XMulti Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XMULTI_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.MultiRefStatementImpl <em>Multi Ref Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.MultiRefStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getMultiRefStatement()
   * @generated
   */
  int MULTI_REF_STATEMENT = 14;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_REF_STATEMENT__STATES = XMULTI_STATEMENT__STATES;

  /**
   * The feature id for the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_REF_STATEMENT__PROPERTY = XMULTI_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Multi Ref Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_REF_STATEMENT_FEATURE_COUNT = XMULTI_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.MultiStatementImpl <em>Multi Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.MultiStatementImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getMultiStatement()
   * @generated
   */
  int MULTI_STATEMENT = 15;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_STATEMENT__STATES = XMULTI_STATEMENT__STATES;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_STATEMENT__PROPERTY = XMULTI_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Multi Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_STATEMENT_FEATURE_COUNT = XMULTI_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link tdt4250.xss.xSS.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see tdt4250.xss.xSS.impl.StateImpl
   * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getState()
   * @generated
   */
  int STATE = 16;

  /**
   * The feature id for the '<em><b>Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__MODIFIER = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__VALUE = 1;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.stylesheet <em>stylesheet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>stylesheet</em>'.
   * @see tdt4250.xss.xSS.stylesheet
   * @generated
   */
  EClass getstylesheet();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.stylesheet#getCustomSelectors <em>Custom Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Custom Selectors</em>'.
   * @see tdt4250.xss.xSS.stylesheet#getCustomSelectors()
   * @see #getstylesheet()
   * @generated
   */
  EReference getstylesheet_CustomSelectors();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.stylesheet#getCustomProperties <em>Custom Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Custom Properties</em>'.
   * @see tdt4250.xss.xSS.stylesheet#getCustomProperties()
   * @see #getstylesheet()
   * @generated
   */
  EReference getstylesheet_CustomProperties();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.XSelector <em>XSelector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSelector</em>'.
   * @see tdt4250.xss.xSS.XSelector
   * @generated
   */
  EClass getXSelector();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.GroupSelector <em>Group Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Selector</em>'.
   * @see tdt4250.xss.xSS.GroupSelector
   * @generated
   */
  EClass getGroupSelector();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.GroupSelector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tdt4250.xss.xSS.GroupSelector#getName()
   * @see #getGroupSelector()
   * @generated
   */
  EAttribute getGroupSelector_Name();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.GroupSelector#getSubSelectors <em>Sub Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Selectors</em>'.
   * @see tdt4250.xss.xSS.GroupSelector#getSubSelectors()
   * @see #getGroupSelector()
   * @generated
   */
  EReference getGroupSelector_SubSelectors();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see tdt4250.xss.xSS.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.Selector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tdt4250.xss.xSS.Selector#getName()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Name();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.XProperty <em>XProperty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XProperty</em>'.
   * @see tdt4250.xss.xSS.XProperty
   * @generated
   */
  EClass getXProperty();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.XProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tdt4250.xss.xSS.XProperty#getName()
   * @see #getXProperty()
   * @generated
   */
  EAttribute getXProperty_Name();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.CustomProperty <em>Custom Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custom Property</em>'.
   * @see tdt4250.xss.xSS.CustomProperty
   * @generated
   */
  EClass getCustomProperty();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.CustomProperty#getSubRule <em>Sub Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Rule</em>'.
   * @see tdt4250.xss.xSS.CustomProperty#getSubRule()
   * @see #getCustomProperty()
   * @generated
   */
  EReference getCustomProperty_SubRule();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.SubRule <em>Sub Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Rule</em>'.
   * @see tdt4250.xss.xSS.SubRule
   * @generated
   */
  EClass getSubRule();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.SubRule#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see tdt4250.xss.xSS.SubRule#getProperty()
   * @see #getSubRule()
   * @generated
   */
  EAttribute getSubRule_Property();

  /**
   * Returns the meta object for the containment reference '{@link tdt4250.xss.xSS.SubRule#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see tdt4250.xss.xSS.SubRule#getExpression()
   * @see #getSubRule()
   * @generated
   */
  EReference getSubRule_Expression();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see tdt4250.xss.xSS.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see tdt4250.xss.xSS.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.GroupProperty <em>Group Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Property</em>'.
   * @see tdt4250.xss.xSS.GroupProperty
   * @generated
   */
  EClass getGroupProperty();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.GroupProperty#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see tdt4250.xss.xSS.GroupProperty#getStatements()
   * @see #getGroupProperty()
   * @generated
   */
  EReference getGroupProperty_Statements();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.XStatement <em>XStatement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XStatement</em>'.
   * @see tdt4250.xss.xSS.XStatement
   * @generated
   */
  EClass getXStatement();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.XSingleStatement <em>XSingle Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSingle Statement</em>'.
   * @see tdt4250.xss.xSS.XSingleStatement
   * @generated
   */
  EClass getXSingleStatement();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.XSingleStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see tdt4250.xss.xSS.XSingleStatement#getValue()
   * @see #getXSingleStatement()
   * @generated
   */
  EAttribute getXSingleStatement_Value();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.SingleRefStatement <em>Single Ref Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Ref Statement</em>'.
   * @see tdt4250.xss.xSS.SingleRefStatement
   * @generated
   */
  EClass getSingleRefStatement();

  /**
   * Returns the meta object for the reference '{@link tdt4250.xss.xSS.SingleRefStatement#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Property</em>'.
   * @see tdt4250.xss.xSS.SingleRefStatement#getProperty()
   * @see #getSingleRefStatement()
   * @generated
   */
  EReference getSingleRefStatement_Property();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.SingleStatement <em>Single Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Statement</em>'.
   * @see tdt4250.xss.xSS.SingleStatement
   * @generated
   */
  EClass getSingleStatement();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.SingleStatement#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see tdt4250.xss.xSS.SingleStatement#getProperty()
   * @see #getSingleStatement()
   * @generated
   */
  EAttribute getSingleStatement_Property();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.XMultiStatement <em>XMulti Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XMulti Statement</em>'.
   * @see tdt4250.xss.xSS.XMultiStatement
   * @generated
   */
  EClass getXMultiStatement();

  /**
   * Returns the meta object for the containment reference list '{@link tdt4250.xss.xSS.XMultiStatement#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see tdt4250.xss.xSS.XMultiStatement#getStates()
   * @see #getXMultiStatement()
   * @generated
   */
  EReference getXMultiStatement_States();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.MultiRefStatement <em>Multi Ref Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multi Ref Statement</em>'.
   * @see tdt4250.xss.xSS.MultiRefStatement
   * @generated
   */
  EClass getMultiRefStatement();

  /**
   * Returns the meta object for the reference '{@link tdt4250.xss.xSS.MultiRefStatement#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Property</em>'.
   * @see tdt4250.xss.xSS.MultiRefStatement#getProperty()
   * @see #getMultiRefStatement()
   * @generated
   */
  EReference getMultiRefStatement_Property();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.MultiStatement <em>Multi Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multi Statement</em>'.
   * @see tdt4250.xss.xSS.MultiStatement
   * @generated
   */
  EClass getMultiStatement();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.MultiStatement#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see tdt4250.xss.xSS.MultiStatement#getProperty()
   * @see #getMultiStatement()
   * @generated
   */
  EAttribute getMultiStatement_Property();

  /**
   * Returns the meta object for class '{@link tdt4250.xss.xSS.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see tdt4250.xss.xSS.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the containment reference '{@link tdt4250.xss.xSS.State#getModifier <em>Modifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modifier</em>'.
   * @see tdt4250.xss.xSS.State#getModifier()
   * @see #getState()
   * @generated
   */
  EReference getState_Modifier();

  /**
   * Returns the meta object for the attribute '{@link tdt4250.xss.xSS.State#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see tdt4250.xss.xSS.State#getValue()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XSSFactory getXSSFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.stylesheetImpl <em>stylesheet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.stylesheetImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getstylesheet()
     * @generated
     */
    EClass STYLESHEET = eINSTANCE.getstylesheet();

    /**
     * The meta object literal for the '<em><b>Custom Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLESHEET__CUSTOM_SELECTORS = eINSTANCE.getstylesheet_CustomSelectors();

    /**
     * The meta object literal for the '<em><b>Custom Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STYLESHEET__CUSTOM_PROPERTIES = eINSTANCE.getstylesheet_CustomProperties();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.XSelectorImpl <em>XSelector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.XSelectorImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXSelector()
     * @generated
     */
    EClass XSELECTOR = eINSTANCE.getXSelector();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.GroupSelectorImpl <em>Group Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.GroupSelectorImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupSelector()
     * @generated
     */
    EClass GROUP_SELECTOR = eINSTANCE.getGroupSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP_SELECTOR__NAME = eINSTANCE.getGroupSelector_Name();

    /**
     * The meta object literal for the '<em><b>Sub Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_SELECTOR__SUB_SELECTORS = eINSTANCE.getGroupSelector_SubSelectors();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.SelectorImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__NAME = eINSTANCE.getSelector_Name();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.XPropertyImpl <em>XProperty</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.XPropertyImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXProperty()
     * @generated
     */
    EClass XPROPERTY = eINSTANCE.getXProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XPROPERTY__NAME = eINSTANCE.getXProperty_Name();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.CustomPropertyImpl <em>Custom Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.CustomPropertyImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getCustomProperty()
     * @generated
     */
    EClass CUSTOM_PROPERTY = eINSTANCE.getCustomProperty();

    /**
     * The meta object literal for the '<em><b>Sub Rule</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM_PROPERTY__SUB_RULE = eINSTANCE.getCustomProperty_SubRule();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.SubRuleImpl <em>Sub Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.SubRuleImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSubRule()
     * @generated
     */
    EClass SUB_RULE = eINSTANCE.getSubRule();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_RULE__PROPERTY = eINSTANCE.getSubRule_Property();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_RULE__EXPRESSION = eINSTANCE.getSubRule_Expression();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.ExpressionImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.GroupPropertyImpl <em>Group Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.GroupPropertyImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getGroupProperty()
     * @generated
     */
    EClass GROUP_PROPERTY = eINSTANCE.getGroupProperty();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_PROPERTY__STATEMENTS = eINSTANCE.getGroupProperty_Statements();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.XStatementImpl <em>XStatement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.XStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXStatement()
     * @generated
     */
    EClass XSTATEMENT = eINSTANCE.getXStatement();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.XSingleStatementImpl <em>XSingle Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.XSingleStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXSingleStatement()
     * @generated
     */
    EClass XSINGLE_STATEMENT = eINSTANCE.getXSingleStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XSINGLE_STATEMENT__VALUE = eINSTANCE.getXSingleStatement_Value();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.SingleRefStatementImpl <em>Single Ref Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.SingleRefStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSingleRefStatement()
     * @generated
     */
    EClass SINGLE_REF_STATEMENT = eINSTANCE.getSingleRefStatement();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINGLE_REF_STATEMENT__PROPERTY = eINSTANCE.getSingleRefStatement_Property();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.SingleStatementImpl <em>Single Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.SingleStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getSingleStatement()
     * @generated
     */
    EClass SINGLE_STATEMENT = eINSTANCE.getSingleStatement();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_STATEMENT__PROPERTY = eINSTANCE.getSingleStatement_Property();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.XMultiStatementImpl <em>XMulti Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.XMultiStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getXMultiStatement()
     * @generated
     */
    EClass XMULTI_STATEMENT = eINSTANCE.getXMultiStatement();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XMULTI_STATEMENT__STATES = eINSTANCE.getXMultiStatement_States();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.MultiRefStatementImpl <em>Multi Ref Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.MultiRefStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getMultiRefStatement()
     * @generated
     */
    EClass MULTI_REF_STATEMENT = eINSTANCE.getMultiRefStatement();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTI_REF_STATEMENT__PROPERTY = eINSTANCE.getMultiRefStatement_Property();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.MultiStatementImpl <em>Multi Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.MultiStatementImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getMultiStatement()
     * @generated
     */
    EClass MULTI_STATEMENT = eINSTANCE.getMultiStatement();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTI_STATEMENT__PROPERTY = eINSTANCE.getMultiStatement_Property();

    /**
     * The meta object literal for the '{@link tdt4250.xss.xSS.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see tdt4250.xss.xSS.impl.StateImpl
     * @see tdt4250.xss.xSS.impl.XSSPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Modifier</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__MODIFIER = eINSTANCE.getState_Modifier();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__VALUE = eINSTANCE.getState_Value();

  }

} //XSSPackage
