/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXSSScopeProvider extends DelegatingScopeProvider {
}
