/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import tdt4250.xss.ide.contentassist.antlr.internal.InternalXSSParser;
import tdt4250.xss.services.XSSGrammarAccess;

public class XSSParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(XSSGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, XSSGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSelectorAccess().getNamesAlternatives_0(), "rule__Selector__NamesAlternatives_0");
			builder.put(grammarAccess.getStylesheetAccess().getGroup(), "rule__Stylesheet__Group__0");
			builder.put(grammarAccess.getGroupSelectorAccess().getGroup(), "rule__GroupSelector__Group__0");
			builder.put(grammarAccess.getGroupSelectorAccess().getGroup_4(), "rule__GroupSelector__Group_4__0");
			builder.put(grammarAccess.getStylesheetAccess().getCustomSelectorsAssignment_1(), "rule__Stylesheet__CustomSelectorsAssignment_1");
			builder.put(grammarAccess.getGroupSelectorAccess().getNameAssignment_1(), "rule__GroupSelector__NameAssignment_1");
			builder.put(grammarAccess.getGroupSelectorAccess().getSubSelectorsAssignment_3(), "rule__GroupSelector__SubSelectorsAssignment_3");
			builder.put(grammarAccess.getGroupSelectorAccess().getSubSelectorsAssignment_4_1(), "rule__GroupSelector__SubSelectorsAssignment_4_1");
			builder.put(grammarAccess.getSelectorAccess().getNamesAssignment(), "rule__Selector__NamesAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private XSSGrammarAccess grammarAccess;

	@Override
	protected InternalXSSParser createParser() {
		InternalXSSParser result = new InternalXSSParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XSSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XSSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
