/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XSSRuntimeModule extends AbstractXSSRuntimeModule {
}
