/*
 * generated by Xtext 2.22.0
 */
package tdt4250.xss.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tdt4250.xss.parser.antlr.internal.InternalXSSParser;
import tdt4250.xss.services.XSSGrammarAccess;

public class XSSParser extends AbstractAntlrParser {

	@Inject
	private XSSGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXSSParser createParser(XtextTokenStream stream) {
		return new InternalXSSParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Stylesheet";
	}

	public XSSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XSSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
